import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../data/catalog_repository.dart';
import '../models.dart';
import '../routes.dart';
import '../util/breakpoints.dart';
import '../widgets/app_shell.dart';

/// Generates a copy-pasteable shell script for flashing a chosen
/// ROM + recovery onto a chosen (brand, codename) device.
///
/// The generator is intentionally conservative: it emits commented-out
/// steps for partition flashes (so the user understands them) and prints
/// the fastboot / adb sequence in order. It does NOT execute anything.
class FlashScriptPage extends StatefulWidget {
  const FlashScriptPage({
    super.key,
    this.initialBrand,
    this.initialCodename,
    this.initialRomId,
    this.initialRecoveryId,
  });

  final String? initialBrand;
  final String? initialCodename;
  final String? initialRomId;
  final String? initialRecoveryId;

  @override
  State<FlashScriptPage> createState() => _FlashScriptPageState();
}

class _FlashScriptPageState extends State<FlashScriptPage> {
  String? _brand;
  String? _codename;
  String? _romId;
  String? _recoveryId;
  bool _wantsGapps = true;
  bool _wantsMagisk = false;
  bool _wipeData = true;

  @override
  void initState() {
    super.initState();
    _brand = widget.initialBrand;
    _codename = widget.initialCodename;
    _romId = widget.initialRomId;
    _recoveryId = widget.initialRecoveryId;
  }

  List<DeviceRef> _devicesForBrand(String? brand) {
    if (brand == null) return const <DeviceRef>[];
    final CatalogRepository repo = CatalogRepository.instance;
    final Map<String, DeviceRef> seen = <String, DeviceRef>{};
    for (final CatalogEntry e in <CatalogEntry>[
      ...repo.roms,
      ...repo.recoveries,
    ]) {
      for (final DeviceRef d in e.devices) {
        if (d.brand != brand || d.codename.isEmpty) continue;
        seen.putIfAbsent(d.codename, () => d);
      }
    }
    final List<DeviceRef> out = seen.values.toList()
      ..sort(
        (DeviceRef a, DeviceRef b) =>
            a.model.toLowerCase().compareTo(b.model.toLowerCase()),
      );
    return out;
  }

  String _generate() {
    final CatalogRepository repo = CatalogRepository.instance;
    final CatalogEntry? rom = _romId == null ? null : repo.romById(_romId!);
    final CatalogEntry? rec =
        _recoveryId == null ? null : repo.recoveryById(_recoveryId!);
    final String device = '$_brand $_codename';
    final StringBuffer b = StringBuffer();
    b.writeln('#!/usr/bin/env bash');
    b.writeln('# Generated by Custom RR · flash-script helper');
    b.writeln('# Device : $device');
    if (rom != null) b.writeln('# ROM    : ${rom.name} (${rom.downloadUrl})');
    if (rec != null) {
      b.writeln('# Recovery: ${rec.name} (${rec.downloadUrl})');
    }
    b.writeln('# Options: gapps=$_wantsGapps, magisk=$_wantsMagisk, '
        'wipeData=$_wipeData');
    b.writeln('#');
    b.writeln('# REVIEW EVERY STEP BEFORE RUNNING. Flashing the wrong file');
    b.writeln('# WILL BRICK YOUR PHONE. Make a full backup first.');
    b.writeln('set -euo pipefail');
    b.writeln();
    b.writeln('# 1. Prereqs (host machine):');
    b.writeln('#    - platform-tools (adb + fastboot) installed and on PATH');
    b.writeln(
      '#    - USB debugging + OEM unlocking enabled in Developer Options',
    );
    b.writeln('#    - Bootloader unlocked for $_brand $_codename');
    b.writeln('#      (see the manufacturer\'s official instructions; some');
    b.writeln('#       brands need a server-side unlock token first.)');
    b.writeln();
    b.writeln('# 2. Place these files in the current directory:');
    if (rec != null) {
      b.writeln(
        '#    - recovery.img       (downloaded from ${rec.downloadUrl})',
      );
    }
    if (rom != null) {
      b.writeln(
        '#    - rom.zip            (downloaded from ${rom.downloadUrl})',
      );
    }
    if (_wantsGapps) {
      b.writeln(
        '#    - gapps.zip          (e.g. MindTheGapps or NikGApps for your Android version)',
      );
    }
    if (_wantsMagisk) {
      b.writeln(
        '#    - magisk.zip         (from https://github.com/topjohnwu/Magisk/releases)',
      );
    }
    b.writeln();
    b.writeln('echo "==> Reboot to bootloader"');
    b.writeln('adb reboot bootloader');
    b.writeln('sleep 8');
    b.writeln();
    if (rec != null) {
      b.writeln('echo "==> Flash custom recovery (${rec.name})"');
      b.writeln(
        '# On A/B devices most projects recommend `fastboot boot` first',
      );
      b.writeln('# to verify the recovery image actually boots before making');
      b.writeln('# it permanent.');
      b.writeln('fastboot boot recovery.img');
      b.writeln(
        '# Once you have confirmed the recovery boots cleanly, you can',
      );
      b.writeln('# flash it permanently from inside the recovery itself, or:');
      b.writeln('#   fastboot flash boot recovery.img      # A/B devices');
      b.writeln('#   fastboot flash recovery recovery.img  # A-only devices');
      b.writeln();
    }
    b.writeln(
      'echo "==> Inside ${rec?.name ?? 'recovery'}, perform these steps"',
    );
    if (_wipeData) {
      b.writeln('#   1) Wipe -> Format Data (yes/erase encryption)');
      b.writeln('#   2) Wipe -> Advanced Wipe -> Dalvik, Cache, System, Data');
    } else {
      b.writeln(
        '#   1) (Optional) Wipe -> Dalvik / Cache to clear stale runtime data',
      );
    }
    b.writeln('#   2) Reboot to recovery again if asked');
    b.writeln('#   3) Install -> rom.zip');
    if (_wantsGapps) {
      b.writeln('#   4) Install -> gapps.zip (do not reboot in between)');
    }
    if (_wantsMagisk) {
      b.writeln(
        '#   5) Install -> magisk.zip (last, so it patches the freshly-flashed boot image)',
      );
    }
    b.writeln('#   6) Reboot system');
    b.writeln();
    b.writeln('# 3. Alternative ADB sideload (if you prefer):');
    b.writeln('#    adb sideload rom.zip');
    if (_wantsGapps) b.writeln('#    adb sideload gapps.zip');
    if (_wantsMagisk) b.writeln('#    adb sideload magisk.zip');
    b.writeln();
    b.writeln(
      '# 4. First boot can take 5-15 minutes while Android optimises apps.',
    );
    b.writeln('#    Do NOT pull the battery / cable during this step.');
    b.writeln();
    b.writeln(
      'echo "==> Done. Verify the build with: getprop ro.build.version.release"',
    );
    return b.toString();
  }

  @override
  Widget build(BuildContext context) {
    final CatalogRepository repo = CatalogRepository.instance;
    final List<String> brands =
        repo.devices.map((DeviceEntry d) => d.name).toList();
    final List<DeviceRef> models = _devicesForBrand(_brand);
    final List<CatalogEntry> roms = _brand == null || _codename == null
        ? repo.roms
        : repo.romsForCodename(_brand!, _codename!);
    final List<CatalogEntry> recs = _brand == null || _codename == null
        ? repo.recoveries
        : repo.recoveriesForCodename(_brand!, _codename!);
    final bool ready = _brand != null &&
        _codename != null &&
        _romId != null &&
        _recoveryId != null;

    return AppShell(
      title: 'Flash script generator',
      selectedRoute: AppRoutes.flashScript,
      body: Center(
        child: ConstrainedBox(
          constraints: const BoxConstraints(
            maxWidth: Breakpoints.readingMaxWidth,
          ),
          child: ListView(
            padding: const EdgeInsets.all(20),
            children: <Widget>[
              Text(
                'Pick your phone and the projects you want to flash. '
                'A copy-pasteable shell script appears below — '
                'review each step before running it.',
                style: Theme.of(context).textTheme.bodyMedium,
              ),
              const SizedBox(height: 16),
              _LabelledDropdown<String>(
                label: 'Brand',
                value: _brand,
                items: brands,
                itemLabel: (String s) => s,
                onChanged: (String? v) => setState(() {
                  _brand = v;
                  _codename = null;
                }),
              ),
              const SizedBox(height: 12),
              _LabelledDropdown<String>(
                label: 'Model / codename',
                value: _codename,
                items: models.map((DeviceRef d) => d.codename).toList(),
                itemLabel: (String c) {
                  final DeviceRef d = models.firstWhere(
                    (DeviceRef m) => m.codename == c,
                    orElse: () =>
                        DeviceRef(brand: _brand ?? '', model: c, codename: c),
                  );
                  return '${d.model}  ·  $c';
                },
                onChanged: models.isEmpty
                    ? null
                    : (String? v) => setState(() => _codename = v),
              ),
              const SizedBox(height: 12),
              _LabelledDropdown<String>(
                label: 'ROM',
                value: _romId,
                items: roms.map((CatalogEntry e) => e.id).toList(),
                itemLabel: (String id) =>
                    roms.firstWhere((CatalogEntry e) => e.id == id).name,
                onChanged: (String? v) => setState(() => _romId = v),
              ),
              const SizedBox(height: 12),
              _LabelledDropdown<String>(
                label: 'Recovery',
                value: _recoveryId,
                items: recs.map((CatalogEntry e) => e.id).toList(),
                itemLabel: (String id) =>
                    recs.firstWhere((CatalogEntry e) => e.id == id).name,
                onChanged: (String? v) => setState(() => _recoveryId = v),
              ),
              const SizedBox(height: 8),
              SwitchListTile(
                title: const Text('Include GApps'),
                subtitle: const Text('Adds a separate gapps.zip flash step.'),
                value: _wantsGapps,
                onChanged: (bool v) => setState(() => _wantsGapps = v),
              ),
              SwitchListTile(
                title: const Text('Include Magisk (root)'),
                subtitle:
                    const Text('Flash Magisk last so it patches the new boot.'),
                value: _wantsMagisk,
                onChanged: (bool v) => setState(() => _wantsMagisk = v),
              ),
              SwitchListTile(
                title: const Text('Wipe data (clean flash)'),
                subtitle: const Text(
                  'Strongly recommended when switching between different ROMs.',
                ),
                value: _wipeData,
                onChanged: (bool v) => setState(() => _wipeData = v),
              ),
              const SizedBox(height: 16),
              if (!ready)
                Card(
                  color: Theme.of(context).colorScheme.surfaceContainerHigh,
                  child: const Padding(
                    padding: EdgeInsets.all(16),
                    child: Text(
                      'Pick a brand, codename, ROM, and recovery to generate '
                      'the script.',
                    ),
                  ),
                )
              else
                _ScriptOutput(text: _generate()),
            ],
          ),
        ),
      ),
    );
  }
}

class _LabelledDropdown<T> extends StatelessWidget {
  const _LabelledDropdown({
    required this.label,
    required this.value,
    required this.items,
    required this.itemLabel,
    required this.onChanged,
  });
  final String label;
  final T? value;
  final List<T> items;
  final String Function(T) itemLabel;
  final ValueChanged<T?>? onChanged;

  @override
  Widget build(BuildContext context) {
    return InputDecorator(
      decoration: InputDecoration(
        labelText: label,
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
        isDense: true,
      ),
      child: DropdownButtonHideUnderline(
        child: DropdownButton<T>(
          value: items.contains(value) ? value : null,
          isExpanded: true,
          hint: Text(items.isEmpty ? '— none available —' : 'Select…'),
          onChanged: items.isEmpty ? null : onChanged,
          items: <DropdownMenuItem<T>>[
            for (final T item in items)
              DropdownMenuItem<T>(value: item, child: Text(itemLabel(item))),
          ],
        ),
      ),
    );
  }
}

class _ScriptOutput extends StatelessWidget {
  const _ScriptOutput({required this.text});
  final String text;

  Future<void> _copy(BuildContext context) async {
    await Clipboard.setData(ClipboardData(text: text));
    if (!context.mounted) return;
    ScaffoldMessenger.of(context).hideCurrentSnackBar();
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('Script copied to clipboard'),
        behavior: SnackBarBehavior.floating,
        duration: Duration(seconds: 2),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final ColorScheme scheme = Theme.of(context).colorScheme;
    return Card(
      clipBehavior: Clip.antiAlias,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
            color: scheme.surfaceContainerHighest,
            child: Row(
              children: <Widget>[
                const Icon(Icons.terminal, size: 18),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    'flash.sh',
                    style: Theme.of(context).textTheme.labelLarge,
                  ),
                ),
                IconButton(
                  tooltip: 'Copy',
                  icon: const Icon(Icons.copy),
                  onPressed: () => _copy(context),
                ),
              ],
            ),
          ),
          Container(
            color: scheme.surface,
            padding: const EdgeInsets.all(12),
            child: SelectableText(
              text,
              style: const TextStyle(
                fontFamily: 'monospace',
                fontSize: 12.5,
                height: 1.4,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
