include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    directives_ordering: true
    avoid_print: true
    sort_child_properties_last: true

analyzer:
  exclude:
    - build/**
    - ios/Pods/**
    - "**/*.g.dart"
    - "**/generated_plugin_registrant.*"
