// Verifies that the committed assets/catalog.json matches what
// tool/sync_catalog.dart would produce *right now*. Used in CI so a PR
// that edits sync_catalog.dart without regenerating the JSON fails fast.
//
// Usage:
//   dart run tool/check_catalog_drift.dart
//
// Exit codes:
//   0  in sync
//   1  drift detected (prints unified diff hint)
//   2  internal error (couldn't run the sync script)

import 'dart:convert';
import 'dart:io';

Future<void> main() async {
  final File committed = File('assets/catalog.json');
  if (!committed.existsSync()) {
    stderr.writeln('check_catalog_drift: assets/catalog.json is missing');
    exit(2);
  }

  // Snapshot the committed JSON.
  final String before = committed.readAsStringSync();

  // Regenerate via the source-of-truth script. It writes back to
  // assets/catalog.json by default.
  final ProcessResult run = await Process.run(
    Platform.resolvedExecutable,
    <String>['run', 'tool/sync_catalog.dart'],
  );
  if (run.exitCode != 0) {
    stderr.writeln('check_catalog_drift: sync_catalog.dart failed');
    stderr.writeln(run.stdout);
    stderr.writeln(run.stderr);
    // Restore the original file so we don't dirty the working tree.
    committed.writeAsStringSync(before);
    exit(2);
  }

  final String after = committed.readAsStringSync();

  if (before == after) {
    stdout.writeln('check_catalog_drift: assets/catalog.json is in sync.');
    return;
  }

  // Drift! Put the committed version back and explain how to fix.
  committed.writeAsStringSync(before);

  // Print a tiny structural summary so CI logs are useful.
  final Map<String, dynamic> a = jsonDecode(before) as Map<String, dynamic>;
  final Map<String, dynamic> b = jsonDecode(after) as Map<String, dynamic>;
  stderr.writeln('check_catalog_drift: DRIFT detected.');
  stderr.writeln('  committed bytes: ${before.length}');
  stderr.writeln('  regenerated bytes: ${after.length}');
  stderr.writeln('  committed top-level keys: ${a.keys.toList()..sort()}');
  stderr.writeln('  regenerated top-level keys: ${b.keys.toList()..sort()}');
  stderr.writeln('');
  stderr.writeln('Run:');
  stderr.writeln('  dart run tool/sync_catalog.dart');
  stderr.writeln('and commit the updated assets/catalog.json.');
  exit(1);
}
