#!/usr/bin/env bash
# Installs the Custom RR Linux desktop build into the current user's home.
# Custom RR — by Monsiu · https://github.com/monsiu/Custom-RR
#
# Usage (from the repo root after `flutter build linux --release`):
#   ./linux/install.sh           # install to ~/.local
#   ./linux/install.sh --uninstall
#
# This is a per-user install — no root required. To uninstall, re-run with
# --uninstall or delete the paths printed at the end.

set -euo pipefail

PREFIX="${PREFIX:-$HOME/.local}"
APP_ID='custom_rr'
APP_NAME='Custom RR'
# Reverse-DNS id used for the .desktop filename, the icon filename and
# the StartupWMClass. Must match the GTK application-id from
# linux/CMakeLists.txt so Wayland compositors can resolve the icon.
DESKTOP_ID='io.github.monsiu.custom_rr'

BUNDLE_DIR="build/linux/x64/release/bundle"
TARGET_DIR="$PREFIX/share/$APP_ID"
BIN_LINK="$PREFIX/bin/$APP_ID"
DESKTOP_FILE="$PREFIX/share/applications/$DESKTOP_ID.desktop"
ICON_BASE="$PREFIX/share/icons/hicolor"
ICON_SIZES=(48 64 128 256 512)

if [[ "${1:-}" == '--uninstall' ]]; then
  rm -rf "$TARGET_DIR" "$BIN_LINK" "$DESKTOP_FILE"
  for sz in "${ICON_SIZES[@]}"; do
    rm -f "$ICON_BASE/${sz}x${sz}/apps/$DESKTOP_ID.png"
  done
  echo "Uninstalled $APP_NAME from $PREFIX"
  exit 0
fi

if [[ ! -x "$BUNDLE_DIR/$APP_ID" ]]; then
  echo "error: $BUNDLE_DIR/$APP_ID not found. Run 'flutter build linux --release' first." >&2
  exit 1
fi

mkdir -p "$TARGET_DIR" "$(dirname "$BIN_LINK")" \
         "$(dirname "$DESKTOP_FILE")"
for sz in "${ICON_SIZES[@]}"; do
  mkdir -p "$ICON_BASE/${sz}x${sz}/apps"
done

# Copy the whole bundle (binary + engine .so + data/ + lib/).
cp -r "$BUNDLE_DIR/." "$TARGET_DIR/"

# Shim in $PATH so `custom_rr` works from the terminal.
ln -sf "$TARGET_DIR/$APP_ID" "$BIN_LINK"

# Desktop entry — rewrite Exec to the absolute path so launchers find it.
sed "s|^Exec=.*|Exec=$TARGET_DIR/$APP_ID|" linux/$DESKTOP_ID.desktop > "$DESKTOP_FILE"
chmod 644 "$DESKTOP_FILE"

# Icon ladder. Source PNGs are pre-generated by tool/regen_icons.sh into
# images/generated/linux/launcher_<size>.png so install does not depend
# on ImageMagick. Falls back to images/launcher.png at 512 if the
# generated set is missing (e.g. fresh checkout that hasn't run regen).
# The filename must match the desktop file's Icon= key (which itself
# matches the GTK application-id) so Wayland compositors can resolve it.
for sz in "${ICON_SIZES[@]}"; do
  src="images/generated/linux/launcher_${sz}.png"
  dest="$ICON_BASE/${sz}x${sz}/apps/$DESKTOP_ID.png"
  if [[ -f "$src" ]]; then
    cp "$src" "$dest"
  elif [[ "$sz" == 512 ]]; then
    cp images/launcher.png "$dest"
  fi
done

# Refresh the desktop database and icon cache so the entry and icon
# appear in app menus without needing a logout. Both are ignored if the
# helpers aren't installed.
if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database "$PREFIX/share/applications" >/dev/null 2>&1 || true
fi
if command -v gtk-update-icon-cache >/dev/null 2>&1; then
  gtk-update-icon-cache -q "$PREFIX/share/icons/hicolor" 2>/dev/null || true
fi

echo "Installed $APP_NAME:"
echo "  bundle:   $TARGET_DIR"
echo "  binary:   $BIN_LINK"
echo "  desktop:  $DESKTOP_FILE"
echo "  icons:    $ICON_BASE/{48,64,128,256,512}x.../apps/$DESKTOP_ID.png"
echo
echo "Launch with: $APP_ID  (or find '$APP_NAME' in your app menu)"
